### PR TITLE
Buggfix! Userstory #2.7 fixa ljud vid klick

### PR DESCRIPTION
**Pull request by OscarAdamsson**
Was a bug with what sound was played when clicking twice on a card.. Solved now, I think

### CODE REVIEW

**Comment by Turbobus** [comment]
I think that the bug is fixed but you can still get a sound to play from the card when it is upside down. 

If you get a wrong answer (So the card flips back facing down) there is a small delay before the card can be activated again and flipped up. In this timeframe you can click on the card facing down and still get a sound to play from that card.

**Comment by Turbobus** [comment]
EDIT

The sound comes from the last card that was flipped up, not the card clicked

**Comment by Danilll01** [comment]
I removed usersettings from this branch by merging in main

**Comment by agnesros** [comment]
Could not discover bug. If it reappears, I believe it is part of a bigger problem with the delays within memory card game. Therefore, I will approve this for now.

**Comment by Turbobus** [comment]
It is better now than before (The bug I talked about is fixed). Still if you click on two cards you can still click on any other card and the sound for the first card you flipped will play (Before they are flipped back). 

I think that if the rework of the underlying code behind the game will happen it will solve a lot of these issues for free as I understand that it is hard right now.

**Pull request merged**
