### PR TITLE
3.38 ljud när man sätter på kläder

### PR DESCRIPTION
**Pull request by OscarAdamsson**
Har lagt till ljud vid påklädnad (dressing). Ljudet fungerar inte för solkrämen, kändes för avancerat att göra för mig då det är en annan mekanism finns fungerar där.. Har dock lagt till ett ljud för solkrämen så man kan implementera om man vill

### CODE REVIEW

**Comment by Turbobus** [comment]
OBS Wait untill merge!! We need to look over the files as it seems that many things have been deleted in this pull request

**Comment by Elin1043** [comment]
Main needs to be merged in again before we can accept the pull request

**Comment by OscarAdamsson** [comment]
I must have done something wrong when merging in main the first time, I will merge in main again

**Comment by OscarAdamsson** [comment]
Now I have merged in main again, seems that I had deleted some of the main changes when I merged in the last time. Was also a change in a termometer script that created a conflict, which I resolved by choosing main as the correct one

**Comment by Danilll01** [comment]
This changed was merged by pull requets #171

**Pull request closed without merging**
