### PR TITLE
#6.6 spela musik

### PR DESCRIPTION
**Pull request by Danilll01**
Added the ability to play placed notes.
There is also a marker to show where exactly what beat the music is playing at.
(Currently a small slide bug when teleporting the marker to the start. But it can be seen as a feature)

### CODE REVIEW

**Comment by Turbobus** [comment]
Fix merge conflicts before able to merge

**Comment by Elin1043** [comment]
Also fix bug that we talked about

**Comment by Danilll01** [comment]
Fixed the bug. Now all the notes gets locked when you press "play"

**Comment by Danilll01** [comment]
[Userstory #6.6 Spela musik](https://trello.com/c/kcU27O4g/64-userstory-66-spela-musik)

**Comment by Turbobus** [comment]
I don't know how you feel but wouldn't it been cool if you could have the music loop play all the time and that you could add/remove notes in real time also?

I understand why the bug was fixed but it could be turned into a nice feature. (As long as it don't cause problems elsewhere)

Another thing that we could add is a feature to move around in the music loop. / Skip forward in the song.

**Comment by Danilll01** [comment]
Yes. If we want those features we can make new userstorys that cover them. We can discuss them at the meeting

**Pull request merged**
